<?php

use Illuminate\Database\Seeder;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('disc_questions')->delete();
        $disc_questions = [
            [
                'id' => 1,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, المهام والمسؤليات توصف ب :',
                'content_en' => 'In this role, Tasks & Responsibilities are described as: ',
                'option_d_ar' => 'مستعجلة',
                'option_d_en' => 'Urgent in Nature',
                'option_i_ar' => 'مختصة بالناس',
                'option_i_en' => 'People related ',
                'option_s_ar' => 'ثابتة',
                'option_s_en' => 'Consistent ',
                'option_c_ar' => 'تفصيلية',
                'option_c_en' => 'Detail-oriented ',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 2,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, طبيعة المهام :',
                'content_en' => 'In this role, ASSIGNMENTS are more: ',
                'option_d_ar' => 'تميل للإنجاز ومحددة الهدف ',
                'option_d_en' => 'Task-Oriented and Purposeful ',
                'option_i_ar' => 'تميل للناس ومتنوعة',
                'option_i_en' => 'People-Oriented and Diverse ',
                'option_s_ar' => 'تميل للناس والإختصاص',
                'option_s_en' => 'People-Oriented and Specialized',
                'option_c_ar' => 'تميل للإنجتاز والإختصاص',
                'option_c_en' => 'Task-Oriented and Specialized ',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 3,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة,  القرارات تتطلب:',
                'content_en' => 'In this role, Decisions will often require:',
                'option_d_ar' => 'ان تكون حازم',
                'option_d_en' => 'Being firm',
                'option_i_ar' => 'أن تسعد الآخرين',
                'option_i_en' => 'Making people happy',
                'option_s_ar' => 'الإهتمام بمشاعر الآخرين',
                'option_s_en' => 'Considering personal feelings',
                'option_c_ar' => 'حساب المخاطر',
                'option_c_en' => 'Calculating risks',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',    

            ],
            [
                'id' => 4,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, القيادة والتأثير يعتمد على ',
                'content_en' => 'In this role, LEADERSHIP AND INFLUENCE will be based deeply on:',
                'option_d_ar' => 'الصلاحيات والمنصب',
                'option_d_en' => 'Authority and Position',
                'option_i_ar' => 'الأمثلة والعواطف',
                'option_i_en' => 'Examples and empathy',
                'option_s_ar' => 'التقبل والمصداقية',
                'option_s_en' => 'Perception and belief level',
                'option_c_ar' => 'منظم ومنطقي',
                'option_c_en' => 'Structure and Logic',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',      
            ],
            [
                'id' => 5,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, عوامل النجاح هي',
                'content_en' => 'In this role, SUCCESS FACTORS are:',
                'option_d_ar' => 'أخذ قرارات بشكل دوري',
                'option_d_en' => 'Taking continues actions',
                'option_i_ar' => 'إبتكار أفكار جديدة',
                'option_i_en' => 'Marketing new ideas',
                'option_s_ar' => 'التسامح مع الإخرين',
                'option_s_en' => 'Tolerance with others',
                'option_c_ar' => 'التخطيط الإستراتيجي',
                'option_c_en' => 'Strategic Planning',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',  
            ],
            [
                'id' => 6,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, توصف بيئة العمل بأنها:',
                'content_en' => 'In this role, THE ENVIRONMENT is:',
                'option_d_ar' => 'تنافسية ومتطلبة',
                'option_d_en' => 'Competitive and demanding',
                'option_i_ar' => 'حماسية ومتغيرة',
                'option_i_en' => 'Energetic and changing',
                'option_s_ar' => 'ودودة و روتنية',
                'option_s_en' => 'Friendly and routine',
                'option_c_ar' => 'قليلة المواجه ومنهجية',
                'option_c_en' => 'low-interaction and methodical',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',   
            ],
            [
                'id' => 7,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, اسلوب العمل يتطلب ',
                'content_en' => 'In this role, THE WORKING STYLE is:',
                'option_d_ar' => 'إتخاذ قررات سريعة',
                'option_d_en' => ' Making Quick decisions',
                'option_i_ar' => 'التفاعل مع الآخرين',
                'option_i_en' => 'Interaction with others',
                'option_s_ar' => 'العمل مع الآخرين',
                'option_s_en' => 'Working with others',
                'option_c_ar' => 'إتباع القوانين',
                'option_c_en' => 'Follow Rules',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',     

            ],
            [
                'id' => 8,
                'slug' => uniqid(),
                'content_ar' => ' في هذه الوظيفة, الأولوية تكون في:',
                'content_en' => 'In this role, THE PRIORITY is : ',
                'option_d_ar' => 'إستخدام السلطة في تحقيق الأهداف',
                'option_d_en' => 'Using authority to reach goals',
                'option_i_ar' => 'رفع معنويات الفريق',
                'option_i_en' => 'Increasing the morale of a team',
                'option_s_ar' => 'إنجاز مهام محددة',
                'option_s_en' => 'Accomplishing predictable assignments',
                'option_c_ar' => 'تحقيق التوقعات',
                'option_c_en' => 'Achieving expectations',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 9,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة,  الصعوبات تحل من خلال:',
                'content_en' => 'In this role, a serious problem will be addressed by:',
                'option_d_ar' => 'القرارات الفورية',
                'option_d_en' => 'An Immediate Decision',
                'option_i_ar' => 'تكليف وإقناع الآخرين',
                'option_i_en' => 'Engaging and persuading others',
                'option_s_ar' => 'أتخاذ خطوات مرنة ومتزنة',
                'option_s_en' => 'Stable & Soft actions',
                'option_c_ar' => 'إتباع الأنظمة والقوانين',
                'option_c_en' => 'Following procedure',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38', 
            ],
            [
                'id' => 10,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, العضو يجب أن يتجنب:',
                'content_en' => 'In this role, A member should AVOID:',
                'option_d_ar' => 'عدم إنتهاز الفرص ونحقيق الأهداف',
                'option_d_en' => 'Not Achieving goals or opportunities',
                'option_i_ar' => 'تطبيق تغيرات جذرية',
                'option_i_en' => ' Apply major changes',
                'option_s_ar' => 'option_s_ar',
                'option_s_en' => 'Losing courtesy with clients',
                'option_c_ar' => 'قلة جودة العمل',
                'option_c_en' => 'Less quality work',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 11,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, العضو تحت الضغوطات يجب أن يكون متمكن في:',
                'content_en' => 'In this role, A member UNDER Pressure should be comfortable in:',
                'option_d_ar' => 'سرعة إتخاذ اللازم',
                'option_d_en' => 'Quickly Move forward',
                'option_i_ar' => 'أن يكون محفذ وإيجابي',
                'option_i_en' => 'To be motivating & positive',
                'option_s_ar' => 'أن يكون صبور',
                'option_s_en' => 'To be patient',
                'option_c_ar' => 'تجنب القرارت السريعة',
                'option_c_en' => 'Avoiding quick decisions',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 12,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, قيمة العضو في الفريق بأن يكون:',
                'content_en' => 'In this role, the value of the member in the team is by being:',
                'option_d_ar' => 'محققا للرؤى المستقبلبة',
                'option_d_en' => 'An achieving visionary',
                'option_i_ar' => 'شخص مؤثر إجابيا',
                'option_i_en' => 'positive influencer',
                'option_s_ar' => 'عضو فريق فعال',
                'option_s_en' => 'A "team player"',
                'option_c_ar' => 'عضو محترف وخبير',
                'option_c_en' => 'An expert & specialized',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 13,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, يتم تحفيذ العضو عن طريق',
                'content_en' => 'In this role, the member will be MOTIVATED BY:',
                'option_d_ar' => 'المهام التي تتخلل تحدياتا',
                'option_d_en' => 'By challenging assignments',
                'option_i_ar' => 'الإلهام والتحفيز',
                'option_i_en' => 'by inspiration and enthusiasm',
                'option_s_ar' => 'التقدير والإشعار بالأهمية',
                'option_s_en' => 'By being appreciated and needed',
                'option_c_ar' => 'بتطبيق الأمور بالطريقه الصحيح',
                'option_c_en' => 'By doing things right',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 14,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيف, الخلافات يجب أن',
                'content_en' => 'In this role, CONFLICTS should be:',
                'option_d_ar' => 'تحل بسرعة',
                'option_d_en' => 'Quickly resolved',
                'option_i_ar' => 'تناقش بموضوعية  لتخفيف حدتها',
                'option_i_en' => 'Talked about openly and reduced',
                'option_s_ar' => 'يتم التعامل معها بكل أريحية',
                'option_s_en' => 'Adapted to resolve issues',
                'option_c_ar' => 'تعالج بدون التدخل المباشر',
                'option_c_en' => 'Delegated without being in-charge ',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 15,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, تكون طريقة التفكير من خلال',
                'content_en' => 'In this role, the member’s way of Mind Procssing is by being:',
                'option_d_ar' => 'التكيف التخطيط المرن ',
                'option_d_en' => 'Adaptive and Fixable in planning',
                'option_i_ar' => ' توفير اللاحظات',
                'option_i_en' => 'Providing feedback',
                'option_s_ar' => 'مراعاة شعور الآخرين',
                'option_s_en' => 'Considering individual’s feelings',
                'option_c_ar' => 'التحليل الدقيق من خلال الأسئلة الإضافية',
                'option_c_en' => 'Accurate Analyzing with additional questions',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 16,
                'slug' => uniqid(),
                'content_ar' => 'في هذه الوظيفة, المهام اليومية يتم إعتبارها بأنها ..',
                'content_en' => 'In this role, the daily Activities can be considered as:',
                'option_d_ar' => 'إتخاذ قرارات متتالية',
                'option_d_en' => 'Solving big problems or making rapid decisions',
                'option_i_ar' => 'تحفيزية للآخرين',
                'option_i_en' => 'Energizing others',
                'option_s_ar' => 'دعم الآخرين',
                'option_s_en' => 'Supporting others',
                'option_c_ar' => 'العمل على مهام محددة ودقيقة',
                'option_c_en' => 'Working on specific, focused tasks',
                'type' => 'role_assessment',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 17,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'صريح\صريحه',
                'option_d_en' => 'Speak Frankly',
                'option_i_ar' => 'يحب المتعة',
                'option_i_en' => 'Likes Fun',
                'option_s_ar' => 'يحب المساعدة',
                'option_s_en' => 'Love to Help',
                'option_c_ar' => 'يحب الرسمية',
                'option_c_en' => 'Formal',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 18,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'جريء\ه',
                'option_d_en' => 'Gutsy',
                'option_i_ar' => 'متفائل ',
                'option_i_en' => 'Always Positive',
                'option_s_ar' => 'عاطفي',
                'option_s_en' => 'Kind Heart',
                'option_c_ar' => 'لايحب لفت الإنتباه',
                'option_c_en' => 'Avoid Attention',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38', 
            ],
            [
                'id' => 19,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'ت\يحب التحديات',
                'option_d_en' => 'Like Challenges',
                'option_i_ar' => 'جذاب',
                'option_i_en' => 'Appealing',
                'option_s_ar' => 'مساند',
                'option_s_en' => 'Supportive',
                'option_c_ar' => 'حذر',
                'option_c_en' => 'Cairful',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38', 

            ],
            [
                'id' => 20,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'تظيحب المواجهة',
                'option_d_en' => 'Like to Confront',
                'option_i_ar' => ' يحب المرح',
                'option_i_en' => 'Animated',
                'option_s_ar' => 'غير أناني',
                'option_s_en' => 'Not Selfish',
                'option_c_ar' => 'يقرر بعناية',
                'option_c_en' => 'Decide Cairfully',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',  
            ],
            [
                'id' => 21,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'تظيحب الإبتكار',
                'option_d_en' => 'Likes Innovtion',
                'option_i_ar' => 'ملهم',
                'option_i_en' => 'Inspiring',
                'option_s_ar' => 'يتأثر بسهولة',
                'option_s_en' => 'Easily Influnced',
                'option_c_ar' => 'يزن المخاطر',
                'option_c_en' => 'Weight Risk',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',

            ],
            [
                'id' => 22,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'مستقل',
                'option_d_en' => 'Independent',
                'option_i_ar' => 'مقنع',
                'option_i_en' => 'Convincing',
                'option_s_ar' => 'لطيف',
                'option_s_en' => 'Kind',
                'option_c_ar' => 'واقعي',
                'option_c_en' => 'unassuming',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',   
            ],
            [
                'id' => 23,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'حاسم',
                'option_d_en' => 'Decisive',
                'option_i_ar' => 'لايقلق',
                'option_i_en' => 'unworried',
                'option_s_ar' => 'يحب المشاركة',
                'option_s_en' => 'Love to Share',
                'option_c_ar' => 'متبع الأنظمة',
                'option_c_en' => 'Follow Rules',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38'
            ],
            [
                'id' => 24,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'نشيط',
                'option_d_en' => 'Energetic',
                'option_i_ar' => 'مضحك',
                'option_i_en' => 'Funny',
                'option_s_ar' => 'متوازن',
                'option_s_en' => 'Balanced',
                'option_c_ar' => 'يفضل العزلة',
                'option_c_en' => 'Prefer Privacy',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',   
            ],
            [
                'id' => 25,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'رائد أعمال',
                'option_d_en' => 'Entrepreneur',
                'option_i_ar' => 'يحب الشهرة',
                'option_i_en' => 'loves to Popularity',
                'option_s_ar' => 'مهتم بالناس',
                'option_s_en' => 'Consider People',
                'option_c_ar' => 'متردد',
                'option_c_en' => 'Hasitant',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38', 
            ],
            [
                'id' => 26,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'عنيد',
                'option_d_en' => 'Stubborn',
                'option_i_ar' => 'كثير الحماس',
                'option_i_en' => 'Excitable',
                'option_s_ar' => 'يرضى بسهولة',
                'option_s_en' => 'Easily Pleased',
                'option_c_ar' => 'دقيق',
                'option_c_en' => 'Exact',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',  

            ],
            [
                'id' => 27,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'حاد',
                'option_d_en' => 'Aggressive',
                'option_i_ar' => 'يثق بالآخرين',
                'option_i_en' => 'Belives in Others',
                'option_s_ar' => 'غير صارم',
                'option_s_en' => 'Not Extreem',
                'option_c_ar' => 'يختار بصعوبة',
                'option_c_en' => 'Picky',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 28,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'لايستسلم',
                'option_d_en' => 'Never Give Up',
                'option_i_ar' => 'يكون صداقات بسهولة',
                'option_i_en' => 'Make Friends Easy',
                'option_s_ar' => 'هادئ',
                'option_s_en' => 'Relaxed',
                'option_c_ar' => 'مقيم',
                'option_c_en' => 'Evaluating',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',   
            ],
            [
                'id' => 29,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'محقق الأهداف',
                'option_d_en' => 'Achive Goals',
                'option_i_ar' => 'يحب التكريم',
                'option_i_en' => 'Seeks Regonition',
                'option_s_ar' => 'رحيم',
                'option_s_en' => 'merciful',
                'option_c_ar' => 'نظامي',
                'option_c_en' => 'Systematic',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ],
            [
                'id' => 30,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'سريع القرارات',
                'option_d_en' => 'Quick Decision',
                'option_i_ar' => 'سريع الحماس',
                'option_i_en' => 'Easly Excited',
                'option_s_ar' => 'محياد',
                'option_s_en' => 'infifferent',
                'option_c_ar' => 'متكيف',
                'option_c_en' => 'Adjustable',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38', 
            ],
            [
                'id' => 31,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'واثق من نفسه ',
                'option_d_en' => 'Confident',
                'option_i_ar' => 'ملفت للإنتباه',
                'option_i_en' => ' Draws Attention',
                'option_s_ar' => 'يتكلم بهدوء',
                'option_s_en' => 'Speak Softly',
                'option_c_ar' => 'غير عجل',
                'option_c_en' => 'unhurried',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',  
            ],
            [
                'id' => 32,
                'slug' => uniqid(),
                'content_ar' => NULL,
                'content_en' => NULL,
                'option_d_ar' => 'متطلب',
                'option_d_en' => 'Demanding',
                'option_i_ar' => 'إجتماعي',
                'option_i_en' => 'Social Person',
                'option_s_ar' => 'قنوع',
                'option_s_en' => 'Pleased',
                'option_c_ar' => 'سريع في ترسيخ الإنطباع',
                'option_c_en' => 'Preciptive',
                'type' => 'personal_coaching',
                'created_at' => '2013-11-29 19:51:38',
                'updated_at' => '2013-11-29 19:51:38',
            ]
        ];
        DB::table('disc_questions')->insert($disc_questions);  
    }
}
